# Generated by Django 3.1 on 2020-08-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200824_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='file_name',
        ),
    ]
